# Generated by Django 4.2.2 on 2023-07-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrammessageidstorage',
            name='ids',
            field=models.JSONField(default=[], verbose_name='Message ids'),
        ),
    ]
