# Generated by Django 4.2.2 on 2023-07-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageids',
            name='ids',
            field=models.JSONField(default=None, verbose_name='Message ids'),
        ),
    ]
