# Generated by Django 4.2.2 on 2023-07-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_alter_telegrammessageidstorage_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrammessageidstorage',
            name='ids',
            field=models.JSONField(default=dict, verbose_name='Message ids'),
        ),
    ]
