[tool.black]
line-length = 119
target-version = ['py311']
include = '\.py?$'
skip-string-normalization = true
exclude = [
     '.eggs',
     '\.git',
     '\.hg',
     '\.mypy_cache',
     '\.tox',
     '\.venv',
     '\.history',
     '_build',
     'buck-out',
     'build',
     'dist',
     'migrations']

[tool.pytest.ini_options]
minversion = "6.0"
env = [
     'NETWORK=TEST'
]
pythonpath = [
     'server',
]
asyncio_mode='auto'
python_files = "tests*.py"
norecursedirs = ["static", ".git"]
python_functions = ["test"]
filterwarnings = [
  'ignore::DeprecationWarning:'
]