version: '3'

services:
  redis:
    build:
      context: ..
      dockerfile: Dockerfile

  rabbitmq:
    build:
      context: ..
      dockerfile: Dockerfile

  postgres-db:
    build:
      context: ..
      dockerfile: Dockerfile

  vault:
    build:
      context: ..
      dockerfile: Dockerfile
