# Generated by Django 4.2.2 on 2023-06-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Password'),
        ),
    ]
