# Generated by Django 4.2.2 on 2023-07-05 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cryptocurrencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=18, max_digits=25, verbose_name='Amount')),
                ('status', models.IntegerField(choices=[(0, 'Created'), (1, 'Cancel'), (2, 'Sent'), (3, 'Done'), (-1, 'Error')], default=0, verbose_name='Status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('confirmed', models.DateTimeField(blank=True, null=True, verbose_name='Confirmed')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='cryptocurrencies.currency', verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='payment', serialize=False, to='orders.order', verbose_name='Order')),
                ('usdt_amount', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='USDT amount')),
                ('usdt_exchange_rate', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='USDT rate')),
                ('usdt_commission', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='USDT commission')),
                ('type', models.CharField(choices=[('by_provider_deposit', 'By provider deposit'), ('deposit', 'Deposit'), ('withdraw', 'Withdraw')], max_length=255, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='transaction', serialize=False, to='orders.order', verbose_name='Order')),
                ('transaction_hash', models.CharField(max_length=255, verbose_name='Transaction hash')),
                ('timestamp', models.IntegerField(verbose_name='Timestamp')),
                ('sender_address', models.CharField(max_length=255, verbose_name='Sender address')),
                ('recipient_address', models.CharField(max_length=255, verbose_name='Recipient address')),
                ('fee', models.DecimalField(decimal_places=18, default=0, max_digits=25, verbose_name='Commission')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
