# Generated by Django 4.2.2 on 2023-07-14 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempwallet',
            name='deposit',
        ),
        migrations.AddField(
            model_name='tempwallet',
            name='payment',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='temp_wallet', serialize=False, to='orders.payment', verbose_name='Payment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tempwallet',
            name='private_key',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Private key'),
        ),
    ]
