# Generated by Django 4.2.2 on 2023-07-05 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.CreateModel(
            name='TempWallet',
            fields=[
                ('deposit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='temp_wallet', serialize=False, to='orders.payment', verbose_name='Deposit')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('private_key', models.CharField(max_length=255, verbose_name='Private key')),
            ],
            options={
                'verbose_name': 'Temp wallet',
                'verbose_name_plural': 'Temp wallets',
            },
        ),
    ]
