# Generated by Django 4.2.2 on 2023-06-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=18, max_digits=25, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fee',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=25, verbose_name='Commission'),
        ),
    ]
