# Generated by Django 4.2.2 on 2023-06-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_amount_alter_transaction_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confirmed'),
        ),
    ]
