# Generated by Django 4.2.2 on 2023-07-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_confirmed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deposit',
            options={'verbose_name': 'Deposit', 'verbose_name_plural': 'Deposits'},
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='commission',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='usd_exchange_rate',
        ),
        migrations.AddField(
            model_name='deposit',
            name='usdt_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='USDT amount'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='usdt_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='USDT commission'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='usdt_exchange_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='USDT rate'),
        ),
    ]
