"""empty message

Revision ID: a7e16479a355
Revises: 
Create Date: 2023-09-08 10:10:58.678216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7e16479a355'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blockchain__network',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('native_symbol', sa.String(length=255), nullable=False),
    sa.Column('native_decimal_place', sa.Integer(), nullable=False),
    sa.Column('node_url', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('family', sa.Enum('evm', 'tron', name='networkfamily'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blockchain__order_provider',
    sa.Column('address', sa.String(length=42), nullable=False),
    sa.Column('abi_type', sa.Enum('ERC20', 'BEP20', 'TRC20', 'EVM_ORDER_PROVIDER', 'TRON_ORDER_PROVIDER', name='abitype'), nullable=True),
    sa.Column('network_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['network_id'], ['blockchain__network.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blockchain__stable_coin',
    sa.Column('address', sa.String(length=42), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('symbol', sa.String(length=255), nullable=True),
    sa.Column('decimal_place', sa.Integer(), nullable=True),
    sa.Column('abi_type', sa.Enum('ERC20', 'BEP20', 'TRC20', 'EVM_ORDER_PROVIDER', 'TRON_ORDER_PROVIDER', name='abitype'), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('network_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['network_id'], ['blockchain__network.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blockchain__stable_coin_address'), 'blockchain__stable_coin', ['address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blockchain__stable_coin_address'), table_name='blockchain__stable_coin')
    op.drop_table('blockchain__stable_coin')
    op.drop_table('blockchain__order_provider')
    op.drop_table('blockchain__network')
    # ### end Alembic commands ###
