"""empty message

Revision ID: 4fd7fc5132bf
Revises: 233d62b6218a
Create Date: 2023-09-19 12:18:01.278627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fd7fc5132bf'
down_revision: Union[str, None] = '233d62b6218a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain__network', sa.Column('short_name', sa.String(length=255), nullable=False))
    op.add_column('exchange_rates__crypto_currency', sa.Column('default_price', sa.Numeric(precision=25, scale=3), nullable=True))
    op.add_column('exchange_rates__fiat_currency', sa.Column('default_price', sa.Numeric(precision=25, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exchange_rates__fiat_currency', 'default_price')
    op.drop_column('exchange_rates__crypto_currency', 'default_price')
    op.drop_column('blockchain__network', 'short_name')
    # ### end Alembic commands ###
