"""empty message

Revision ID: 807bdb1b6f3b
Revises: 4fd7fc5132bf
Create Date: 2023-09-19 12:22:23.403245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '807bdb1b6f3b'
down_revision: Union[str, None] = '4fd7fc5132bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain__stable_coin', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blockchain__stable_coin', 'is_active')
    # ### end Alembic commands ###
