"""empty message

Revision ID: c42371aa8c16
Revises: 078e756afe1e
Create Date: 2023-09-13 17:17:42.111336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c42371aa8c16'
down_revision: Union[str, None] = 'a7e16479a355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates__crypto_currency',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('coin_gecko_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exchange_rates__fiat_currency',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exchange_rates__fiat_currency')
    op.drop_table('exchange_rates__crypto_currency')
    # ### end Alembic commands ###
