# Generated by Django 4.2.2 on 2023-06-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='block_explorer_url',
            field=models.URLField(blank=True, null=True, verbose_name='Block explorer url'),
        ),
    ]
