# Generated by Django 4.2.2 on 2023-07-12 05:56

from django.db import migrations


NETWORKS = [
    {
        'id': 1,
        'name': 'Tron',
    },
    {
        'id': 2,
        'name': 'BSC',
    },
    {
        'id': 3,
        'name': 'ETH',
    }
]

CURRENCIES = [
    {
        'name': 'Tron',
        'symbol': 'TRX',
        'decimal_place': 6,
        'network_id': 1,
        'exchange_id': 'TRX',
    },
    {
        'name': 'Binance smart chain',
        'symbol': 'BNB',
        'decimal_place': 18,
        'network_id': 2,
        'exchange_id': 'BNB',
    },
    {
        'name': 'Ethereum',
        'symbol': 'ETH',
        'decimal_place': 18,
        'network_id': 3,
        'exchange_id': 'ETH',
    }
]


def forward(apps, schema_editor):
    Network = apps.get_model('cryptocurrencies', 'Network')
    Currency = apps.get_model('cryptocurrencies', 'Currency')

    Network.objects.bulk_create([
        Network(**network)
        for network in NETWORKS
    ])

    Currency.objects.bulk_create([
        Currency(**currency)
        for currency in CURRENCIES
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrencies', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
