# Generated by Django 4.2.2 on 2023-06-21 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('network', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='provider', serialize=False, to='cryptocurrencies.network', verbose_name='Network')),
                ('address', models.CharField(max_length=255, verbose_name='Contract address')),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
            },
        ),
    ]
