# Generated by Django 4.2.2 on 2023-07-12 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrencies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='coin_gecko_id',
            new_name='exchange_id',
        ),
    ]
