version: '3'

services:
  tron_api:
    build:
      context: api/
      dockerfile: Dockerfile
    container_name: tron_api
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    env_file:
      - ./.env
    ports:
      - "82:8000"
    expose:
      - 82
    networks:
      - tron_net
    volumes:
      - ./src/files:/home/app/files
    logging:
      options:
        max-size: 100m

  tron_demon:
    build:
      context: transaction_demon/
      dockerfile: Dockerfile
    container_name: tron_demon
    command: /usr/bin/supervisord
    env_file:
      - ./.env
    networks:
      - tron_net
    volumes:
      - ./files:/home/app/files
    logging:
      options:
        max-size: 100m
        
  tron_balancer: 
    build:
      context: balancer/
      dockerfile: Dockerfile
    container_name: tron_balancer
    command: /usr/bin/supervisord
    env_file:
      - ./.env
    networks:
      - tron_net
    volumes:
      - ./files:/home/app/files
    logging:
      options:
        max-size: 100m

networks:
  tron_net:
    driver: bridge